'use strict';

const { SUBJECTS, DIFFICULTIES } = require('../../config/constants');

const opts = (a, b, c, d) => [
  { key: 'A', text: a },
  { key: 'B', text: b },
  { key: 'C', text: c },
  { key: 'D', text: d },
];

module.exports = [
  // ---------------- Maths · Class 9 ----------------
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Linear Equations', difficulty: DIFFICULTIES.EASY,
    questionText: 'Solve for x: x + 5 = 12.',
    options: opts('5', '7', '12', '17'),
    correctOption: 'B',
    explanation: 'Subtract 5 from both sides: x = 12 - 5 = 7.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Linear Equations', difficulty: DIFFICULTIES.EASY,
    questionText: 'If 2x - 3 = 7, then x equals:',
    options: opts('2', '4', '5', '10'),
    correctOption: 'C',
    explanation: '2x = 10, so x = 5.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Polynomials', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'What is the degree of the polynomial 3x^4 + 2x^2 - x + 7?',
    options: opts('2', '3', '4', '7'),
    correctOption: 'C',
    explanation: 'The highest power of x is 4.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Polynomials', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Expand: (x + 2)(x - 2).',
    options: opts('x^2 - 4', 'x^2 + 4', 'x^2 - 2x - 4', 'x^2 + 4x - 4'),
    correctOption: 'A',
    explanation: 'Difference of squares: (x+a)(x-a) = x^2 - a^2.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Polynomials', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Factor: x^2 - 9.',
    options: opts('(x-3)(x-3)', '(x+3)(x+3)', '(x-3)(x+3)', '(x-9)(x+1)'),
    correctOption: 'C',
    explanation: 'Difference of squares: x^2 - 3^2 = (x-3)(x+3).',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Number Systems', difficulty: DIFFICULTIES.EASY,
    questionText: 'Which of the following is an irrational number?',
    options: opts('0.5', '3/4', '√2', '-7'),
    correctOption: 'C',
    explanation: '√2 cannot be expressed as p/q with integer p, q.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Number Systems', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'The decimal 0.3333... is equal to:',
    options: opts('1/2', '1/3', '3/10', '1/4'),
    correctOption: 'B',
    explanation: 'Repeating 3s after the decimal point equals 1/3.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Coordinate Geometry', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Distance from the origin to the point (3, 4) is:',
    options: opts('5', '7', '12', '25'),
    correctOption: 'A',
    explanation: '√(3^2 + 4^2) = √25 = 5.',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Coordinate Geometry', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Midpoint of the segment joining (2, 4) and (6, 8) is:',
    options: opts('(3, 5)', '(4, 6)', '(8, 12)', '(2, 4)'),
    correctOption: 'B',
    explanation: 'Midpoint = ((2+6)/2, (4+8)/2) = (4, 6).',
  },
  {
    subject: SUBJECTS.MATHS, class: 9, topic: 'Linear Equations', difficulty: DIFFICULTIES.EASY,
    questionText: 'If y = 2x + 3, what is y when x = 4?',
    options: opts('7', '8', '11', '14'),
    correctOption: 'C',
    explanation: 'y = 2(4) + 3 = 11.',
  },

  // ---------------- Physics · Class 11 ----------------
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Kinematics', difficulty: DIFFICULTIES.EASY,
    questionText: 'The SI unit of acceleration is:',
    options: opts('m/s', 'm/s^2', 'kg·m/s', 'N'),
    correctOption: 'B',
    explanation: 'Acceleration is rate of change of velocity, measured in m/s^2.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Kinematics', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'A body thrown vertically upward has, at its highest point, a kinetic energy that is:',
    options: opts('Maximum', 'Equal to potential energy at start', 'Zero', 'Half of initial'),
    correctOption: 'C',
    explanation: 'At the apex, vertical velocity is zero, so KE = ½mv^2 = 0.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: "Newton's Laws", difficulty: DIFFICULTIES.EASY,
    questionText: "Newton's second law of motion is best expressed by which equation?",
    options: opts('F = m + a', 'F = m - a', 'F = m · a', 'F = m / a'),
    correctOption: 'C',
    explanation: 'Net force equals mass times acceleration.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: "Newton's Laws", difficulty: DIFFICULTIES.MEDIUM,
    questionText: "Newton's third law states that every action has an equal and ___ reaction.",
    options: opts('parallel', 'opposite', 'larger', 'delayed'),
    correctOption: 'B',
    explanation: 'Equal in magnitude, opposite in direction, on different bodies.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Work and Energy', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Work done by a constant force F moving an object through displacement d in the direction of F is:',
    options: opts('F + d', 'F · d', 'F / d', 'F^2 · d'),
    correctOption: 'B',
    explanation: 'W = F · d when force and displacement are aligned.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Work and Energy', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'According to the work–energy theorem, the net work done on a body equals:',
    options: opts('Change in momentum', 'Change in kinetic energy', 'Change in potential energy', 'Total mechanical energy'),
    correctOption: 'B',
    explanation: 'W_net = ΔKE.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Circular Motion', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'For an object in uniform circular motion, the centripetal force is directed:',
    options: opts('Tangent to the circle', 'Away from the center', 'Toward the center', 'Along velocity'),
    correctOption: 'C',
    explanation: 'Centripetal means "center-seeking"; the force points to the center.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Momentum', difficulty: DIFFICULTIES.EASY,
    questionText: 'Linear momentum p of an object of mass m moving with velocity v is:',
    options: opts('p = m + v', 'p = m · v', 'p = m / v', 'p = ½ m v^2'),
    correctOption: 'B',
    explanation: 'By definition, p = m·v.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: 'Kinematics', difficulty: DIFFICULTIES.EASY,
    questionText: 'Approximate value of acceleration due to gravity near Earth\'s surface:',
    options: opts('1.0 m/s^2', '4.9 m/s^2', '9.8 m/s^2', '98 m/s^2'),
    correctOption: 'C',
    explanation: 'g ≈ 9.8 m/s^2.',
  },
  {
    subject: SUBJECTS.PHYSICS, class: 11, topic: "Newton's Laws", difficulty: DIFFICULTIES.HARD,
    questionText: 'A 2 kg block on a frictionless surface is pushed with a 10 N horizontal force. Its acceleration is:',
    options: opts('2 m/s^2', '5 m/s^2', '10 m/s^2', '20 m/s^2'),
    correctOption: 'B',
    explanation: 'a = F/m = 10/2 = 5 m/s^2.',
  },

  // ---------------- Chemistry · Class 9 ----------------
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Matter', difficulty: DIFFICULTIES.EASY,
    questionText: 'How many classical states of matter are commonly studied at this level?',
    options: opts('1', '2', '3', '5'),
    correctOption: 'C',
    explanation: 'Solid, liquid, and gas — three classical states.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Atomic Structure', difficulty: DIFFICULTIES.EASY,
    questionText: 'The chemical formula of water is:',
    options: opts('H2O', 'HO', 'H2O2', 'OH'),
    correctOption: 'A',
    explanation: 'Two hydrogen atoms and one oxygen atom: H2O.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Atomic Structure', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Which scientist is credited with the modern atomic theory?',
    options: opts('Newton', 'Dalton', 'Einstein', 'Mendel'),
    correctOption: 'B',
    explanation: "Dalton proposed the atomic theory in the early 1800s.",
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Atomic Structure', difficulty: DIFFICULTIES.EASY,
    questionText: 'The nucleus of an atom contains:',
    options: opts('Only electrons', 'Protons and neutrons', 'Protons and electrons', 'Only neutrons'),
    correctOption: 'B',
    explanation: 'Protons (positive) and neutrons (neutral) sit in the nucleus.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Atomic Structure', difficulty: DIFFICULTIES.EASY,
    questionText: 'The charge on an electron is:',
    options: opts('Positive', 'Negative', 'Neutral', 'Variable'),
    correctOption: 'B',
    explanation: 'Electrons carry a negative elementary charge.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Atomic Structure', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'The maximum number of electrons that can fit in the K shell is:',
    options: opts('2', '8', '18', '32'),
    correctOption: 'A',
    explanation: '2n^2 with n=1 gives 2 electrons.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Mole Concept', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'One mole of any substance contains approximately how many particles?',
    options: opts('6.022 × 10^21', '6.022 × 10^23', '3.011 × 10^22', '1.000 × 10^24'),
    correctOption: 'B',
    explanation: "Avogadro's number is 6.022 × 10^23.",
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Mole Concept', difficulty: DIFFICULTIES.HARD,
    questionText: 'The molar mass of CO2 (C = 12, O = 16) is:',
    options: opts('22 g/mol', '28 g/mol', '44 g/mol', '60 g/mol'),
    correctOption: 'C',
    explanation: '12 + 2 × 16 = 44 g/mol.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Matter', difficulty: DIFFICULTIES.EASY,
    questionText: 'Which is NOT a property of solids?',
    options: opts('Definite shape', 'Definite volume', 'Highly compressible', 'Tightly packed particles'),
    correctOption: 'C',
    explanation: 'Solids are generally incompressible because particles are packed tightly.',
  },
  {
    subject: SUBJECTS.CHEMISTRY, class: 9, topic: 'Mole Concept', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'How many atoms are present in one molecule of H2O?',
    options: opts('1', '2', '3', '4'),
    correctOption: 'C',
    explanation: 'Two H atoms plus one O atom = 3 atoms.',
  },

  // ---------------- English · Class 10 ----------------
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Vocabulary', difficulty: DIFFICULTIES.EASY,
    questionText: 'Choose the synonym of "happy":',
    options: opts('Sad', 'Joyful', 'Tired', 'Angry'),
    correctOption: 'B',
    explanation: 'Joyful means full of joy — synonymous with happy.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Vocabulary', difficulty: DIFFICULTIES.EASY,
    questionText: 'Choose the antonym of "rapid":',
    options: opts('Quick', 'Speedy', 'Slow', 'Fast'),
    correctOption: 'C',
    explanation: 'Slow is the opposite of rapid.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Vocabulary', difficulty: DIFFICULTIES.EASY,
    questionText: 'Choose the synonym of "difficult":',
    options: opts('Easy', 'Simple', 'Hard', 'Plain'),
    correctOption: 'C',
    explanation: 'Hard means difficult.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Grammar', difficulty: DIFFICULTIES.EASY,
    questionText: 'Choose the correct verb form: "She ___ to school every day."',
    options: opts('go', 'goes', 'going', 'gone'),
    correctOption: 'B',
    explanation: 'Third-person singular present tense takes "goes".',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Grammar', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Convert to passive voice: "John kicked the ball."',
    options: opts(
      'The ball was kicked by John.',
      'The ball is kicked by John.',
      'John was kicking the ball.',
      'The ball kicked John.'
    ),
    correctOption: 'A',
    explanation: 'Past simple passive: object + was/were + past participle + by + subject.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Grammar', difficulty: DIFFICULTIES.EASY,
    questionText: 'Choose the correct article: "I saw ___ elephant at the zoo."',
    options: opts('a', 'an', 'the', 'no article'),
    correctOption: 'B',
    explanation: '"Elephant" begins with a vowel sound, so use "an".',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Grammar', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'The plural of "mouse" (the animal) is:',
    options: opts('Mouses', 'Mices', 'Mice', 'Mouse'),
    correctOption: 'C',
    explanation: '"Mice" is the irregular plural for the rodent.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Reading Comprehension', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'In the sentence "He was tired, but he kept walking," the word "but" indicates:',
    options: opts('Cause', 'Contrast', 'Time', 'Addition'),
    correctOption: 'B',
    explanation: '"But" introduces a contrast or unexpected continuation.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Grammar', difficulty: DIFFICULTIES.EASY,
    questionText: 'Identify the noun in: "The cat sat on the mat."',
    options: opts('Sat', 'On', 'Cat', 'The'),
    correctOption: 'C',
    explanation: '"Cat" is a common noun naming an animal.',
  },
  {
    subject: SUBJECTS.ENGLISH, class: 10, topic: 'Grammar', difficulty: DIFFICULTIES.EASY,
    questionText: 'Which punctuation mark ends a question?',
    options: opts('. (period)', ', (comma)', '? (question mark)', '! (exclamation)'),
    correctOption: 'C',
    explanation: 'A question is ended by a question mark.',
  },

  // ---------------- Biology · Class 9 ----------------
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.EASY,
    questionText: 'Who first discovered cells while observing cork under a microscope?',
    options: opts('Charles Darwin', 'Robert Hooke', 'Gregor Mendel', 'Louis Pasteur'),
    correctOption: 'B',
    explanation: 'Robert Hooke (1665) coined the term "cell".',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.EASY,
    questionText: 'The basic structural and functional unit of life is the:',
    options: opts('Tissue', 'Organ', 'Cell', 'Organelle'),
    correctOption: 'C',
    explanation: 'All living organisms are composed of cells.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.EASY,
    questionText: 'A rigid cell wall is found in:',
    options: opts('Animal cells only', 'Plant cells', 'Red blood cells', 'Nerve cells'),
    correctOption: 'B',
    explanation: 'Plant cells have a cellulose cell wall; animal cells do not.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Which organelle is often called the "powerhouse of the cell"?',
    options: opts('Nucleus', 'Ribosome', 'Mitochondrion', 'Golgi apparatus'),
    correctOption: 'C',
    explanation: 'Mitochondria generate most of the cell\'s ATP.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'Photosynthesis takes place in which organelle?',
    options: opts('Mitochondrion', 'Chloroplast', 'Nucleus', 'Lysosome'),
    correctOption: 'B',
    explanation: 'Chloroplasts contain chlorophyll, which captures light energy.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.EASY,
    questionText: 'In a eukaryotic cell, DNA is primarily found in the:',
    options: opts('Cytoplasm', 'Nucleus', 'Cell membrane', 'Vacuole'),
    correctOption: 'B',
    explanation: 'The nucleus stores genetic material in eukaryotes.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Tissues', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'The longest cell in the human body is the:',
    options: opts('Skin cell', 'Muscle cell', 'Neuron', 'Red blood cell'),
    correctOption: 'C',
    explanation: 'Neurons (nerve cells) can extend over a meter in length.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Tissues', difficulty: DIFFICULTIES.EASY,
    questionText: 'Which connective tissue carries oxygen throughout the body?',
    options: opts('Bone', 'Cartilage', 'Blood', 'Adipose'),
    correctOption: 'C',
    explanation: 'Blood transports oxygen via hemoglobin in red blood cells.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Diversity in Living Organisms', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'In the five-kingdom classification, bacteria are placed in the kingdom:',
    options: opts('Protista', 'Fungi', 'Plantae', 'Monera'),
    correctOption: 'D',
    explanation: 'Prokaryotes such as bacteria belong to Monera.',
  },
  {
    subject: SUBJECTS.BIOLOGY, class: 9, topic: 'Cell', difficulty: DIFFICULTIES.MEDIUM,
    questionText: 'The nucleus of a cell primarily acts as the:',
    options: opts('Energy producer', 'Control center', 'Waste disposer', 'Protein synthesizer'),
    correctOption: 'B',
    explanation: 'The nucleus controls cell activities and houses DNA.',
  },
];
